ns check

diff --git a/.github/workflows/second-actions.yml b/.github/workflows/second-actions.yml
--- a/.github/workflows/second-actions.yml
+++ b/.github/workflows/second-actions.yml
@@ -1,5 +1,5 @@
 name: after-workflow-1
-on: push
+on: [push , workflow_dispatch] 
 jobs:
     first:
         runs-on: ubuntu-latest
@@ -38,10 +38,15 @@ jobs:
         -   name: changing k8 manifests sql
             run:  |
                 cd k8s
-                kubectl apply -n assignment -f mysql-deployment.yml
-                kubectl apply -n assignment -f mysql-configmap.yml
-                kubectl apply -n assignment -f mysql-secrets.yml
-                kubectl apply -n assignment -f mysql-svc.yml                
+                kubectl get ns assignment || echo ""not found" > checkns.txt
+                if grep -q "not found" checkns.txt; then
+                    kubectl create ns assignment
+                else
+                    kubectl apply -n assignment -f mysql-deployment.yml
+                    kubectl apply -n assignment -f mysql-configmap.yml
+                    kubectl apply -n assignment -f mysql-secrets.yml
+                    kubectl apply -n assignment -f mysql-svc.yml
+                fi                
             #   
                         
         -   name: changing k8 manifests app
